AWSTemplateFormatVersion: 2010-09-09
Resources:
  InsuranceDDBUserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: insurance-user-table
      AttributeDefinitions:
        - AttributeName: "email"
          AttributeType: "S"
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "type"
          AttributeType: "S"
        - AttributeName: "brokerId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "email"
          KeyType: "HASH"
        - AttributeName: "id"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: "type-email-index"
          KeySchema:
            - AttributeName: "type"
              KeyType: "HASH"
            - AttributeName: "email"
              KeyType: "RANGE"
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - id
              - name
              - creditCards
              - status
              - phoneNumber
          ProvisionedThroughput:
            ReadCapacityUnits: 0
            WriteCapacityUnits: 0
        - IndexName: "type-brokerId-index"
          KeySchema:
            - AttributeName: "type"
              KeyType: "HASH"
            - AttributeName: "brokerId"
              KeyType: "RANGE"
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - id
              - email
              - name
              - creditCards
              - status
              - phoneNumber
          ProvisionedThroughput:
            ReadCapacityUnits: 0
            WriteCapacityUnits: 0
  InsuranceDDBPaymentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: insurance-payments-table
      AttributeDefinitions:
        - AttributeName: "email"
          AttributeType: "S"
        - AttributeName: "brokerEmail"
          AttributeType: "S"
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "status-date"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "email"
          KeyType: "HASH"
        - AttributeName: "id"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: "email-status-date-index"
          KeySchema:
            - AttributeName: "email"
              KeyType: "HASH"
            - AttributeName: "status-date"
              KeyType: "RANGE"
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - id
              - date
              - amount
              - status
              - brokerName
              - details
              - dueDate
              - insurer
              - brokerEmail
          ProvisionedThroughput:
            ReadCapacityUnits: 0
            WriteCapacityUnits: 0
        - IndexName: "brokerEmail-status-date-index"
          KeySchema:
            - AttributeName: "brokerEmail"
              KeyType: "HASH"
            - AttributeName: "status-date"
              KeyType: "RANGE"
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - id
              - date
              - amount
              - status
              - brokerName
              - details
              - dueDate
              - insurer
              - email
              - name
          ProvisionedThroughput:
            ReadCapacityUnits: 0
            WriteCapacityUnits: 0
