AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  wallets

  Sample SAM Template for wallets

Parameters:
  EnvironmentValue:
    AllowedValues:
      - dev
      - prod
    Description: Ambiente a desplegar
    Type: String

Mappings: 
  Environments:
    dev:
      UserTable: insurance-user-table
      PaymentsTable: insurance-payments-table
      InsurersTable: insurance-insurers-table
      LambdaBasePolicy: arn:aws:iam::166472935010:policy/AWSLambdaFullAccessCustom
      StageName: dev
      PythonLayer1: arn:aws:lambda:us-east-1:166472935010:layer:PythonLayer1:1
    prod:
      UserTable: insurance-user-table
      PaymentsTable: insurance-payments-table
      InsurersTable: insurance-insurers-table
      LambdaBasePolicy: arn:aws:iam::166472935010:policy/AWSLambdaFullAccessCustom
      StageName: dev
      PythonLayer1: arn:aws:lambda:us-east-1:166472935010:layer:PythonLayer1:1

Conditions:
  CreateProdResources: !Equals [!Ref EnvironmentValue, dev]

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 180
    MemorySize: 128
    Runtime: python3.8
    Handler: app.lambda_handler

Resources:
  InsuranceAWSHttpApiGateway:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref EnvironmentValue
      #Auth:
      #  Authorizers:
      #    FirebaseAuthorizer:
      #      JwtConfiguration:
      #        issuer: "https://securetoken.google.com/dev-tienditas"
      #        audience:
      #          - dev-tienditas
      #      IdentitySource: "$request.header.Authorization"
      #  DefaultAuthorizer: FirebaseAuthorizer
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - POST
          - DELETE
          - PUT
          - OPTIONS
          - PATCH
        MaxAge: 0
        AllowHeaders:
          - Origin
          - X-Requested-With
          - Content-Type
          - Accept

# USER
  InsuranceCreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: InsuranceCreateUserFunction
      Description: Function that creates a user
      Policies:
        - !If [CreateProdResources, !FindInMap [Environments, prod, LambdaBasePolicy], !FindInMap [Environments, dev, LambdaBasePolicy] ]
      Layers:
        - !If [CreateProdResources, !FindInMap [Environments, prod, PythonLayer1], !FindInMap [Environments, dev, PythonLayer1] ]
      CodeUri: user/v1/create_user
      Environment:
        Variables:
          DYNAMODB_USER_TABLE: !If [CreateProdResources, !FindInMap [Environments, prod, UserTable], !FindInMap [Environments, dev, UserTable]]
      Events:
        CreateUserApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref InsuranceAWSHttpApiGateway
            Path: /api/v1/user
            Method: post
  InsuranceGetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: InsuranceGetUserFunction
      Description: Function that get a user
      Policies:
        - !If [CreateProdResources, !FindInMap [Environments, prod, LambdaBasePolicy], !FindInMap [Environments, dev, LambdaBasePolicy] ]
      CodeUri: user/v1/get_user
      Environment:
        Variables:
          DYNAMODB_USER_TABLE: !If [CreateProdResources, !FindInMap [Environments, prod, UserTable], !FindInMap [Environments, dev, UserTable]]
      Events:
        GetUserApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref InsuranceAWSHttpApiGateway
            Path: /api/v1/user
            Method: get
  InsuranceDeleteUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: InsuranceDeleteUserFunction
      Description: Function that get a user
      Policies:
        - !If [CreateProdResources, !FindInMap [Environments, prod, LambdaBasePolicy], !FindInMap [Environments, dev, LambdaBasePolicy] ]
      CodeUri: user/v1/delete_user
      Environment:
        Variables:
          DYNAMODB_USER_TABLE: !If [CreateProdResources, !FindInMap [Environments, prod, UserTable], !FindInMap [Environments, dev, UserTable]]
      Events:
        DeleteUserApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref InsuranceAWSHttpApiGateway
            Path: /api/v1/user
            Method: delete
  InsuranceUpdateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: InsuranceUpdateUserFunction
      Description: Function that updates a user
      Policies:
        - !If [CreateProdResources, !FindInMap [Environments, prod, LambdaBasePolicy], !FindInMap [Environments, dev, LambdaBasePolicy] ]
      CodeUri: user/v1/update_user
      Environment:
        Variables:
          DYNAMODB_USER_TABLE: !If [CreateProdResources, !FindInMap [Environments, prod, UserTable], !FindInMap [Environments, dev, UserTable]]
      Events:
        UpdateUserApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref InsuranceAWSHttpApiGateway
            Path: /api/v1/user
            Method: put

# PAYMENTS
  InsuranceCreatePaymentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: InsuranceCreatePaymentsFunction
      Description: Function that creates a payment
      Policies:
        - !If [CreateProdResources, !FindInMap [Environments, prod, LambdaBasePolicy], !FindInMap [Environments, dev, LambdaBasePolicy] ]
      Layers:
        - !If [CreateProdResources, !FindInMap [Environments, prod, PythonLayer1], !FindInMap [Environments, dev, PythonLayer1] ]
      CodeUri: payments/v1/create_payments
      Environment:
        Variables:
          DYNAMODB_PAYMENTS_TABLE: !If [CreateProdResources, !FindInMap [Environments, prod, PaymentsTable], !FindInMap [Environments, dev, PaymentsTable]]
      Events:
        CreatePaymentsApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref InsuranceAWSHttpApiGateway
            Path: /api/v1/payments
            Method: post
  InsuranceGetPaymentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: InsuranceGetPaymentsFunction
      Description: Function that get payments
      Policies:
        - !If [CreateProdResources, !FindInMap [Environments, prod, LambdaBasePolicy], !FindInMap [Environments, dev, LambdaBasePolicy] ]
      CodeUri: payments/v1/get_payments
      Environment:
        Variables:
          DYNAMODB_PAYMENTS_TABLE: !If [CreateProdResources, !FindInMap [Environments, prod, PaymentsTable], !FindInMap [Environments, dev, PaymentsTable]]
      Events:
        GetPaymentsApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref InsuranceAWSHttpApiGateway
            Path: /api/v1/payments
            Method: get
  InsuranceDeletePaymentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: InsuranceDeletePaymentsFunction
      Description: Function that get payments
      Policies:
        - !If [CreateProdResources, !FindInMap [Environments, prod, LambdaBasePolicy], !FindInMap [Environments, dev, LambdaBasePolicy] ]
      CodeUri: payments/v1/delete_payments
      Environment:
        Variables:
          DYNAMODB_PAYMENTS_TABLE: !If [CreateProdResources, !FindInMap [Environments, prod, PaymentsTable], !FindInMap [Environments, dev, PaymentsTable]]
      Events:
        DeletePaymentsApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref InsuranceAWSHttpApiGateway
            Path: /api/v1/payments
            Method: delete